name: Execute Notebook
name: Execute Notebook

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # This is the fix!

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install notebook nbconvert ipykernel nbformat==5.4.0 jupyter-client==6.1.12

      - name: Execute demo.ipynb
        run: |
          jupyter nbconvert --to notebook --execute demo.ipynb --output executed_demo.ipynb

      - name: Commit and push executed notebook
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add executed_demo.ipynb
          git commit -m "🤖 Auto-commit executed notebook" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install notebook nbconvert ipykernel nbformat==5.4.0 jupyter-client==6.1.12

      - name: Execute demo.ipynb
        run: |
          jupyter nbconvert --to notebook --execute demo.ipynb --output executed_demo.ipynb

      - name: Commit and push executed notebook
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add executed_demo.ipynb
          git commit -m "🤖 Auto-commit executed notebook" || echo "No changes"
          git push

