name: Execute Notebook

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install notebook nbconvert ipykernel nbformat==5.4.0 jupyter-client==6.1.12

      - name: Execute demo.ipynb
        run: |
          jupyter nbconvert --to notebook --execute demo.ipynb --output executed_demo.ipynb
